config/routes.rb
Rails.application.routes.draw do
  root to: 'blogs#index'

  resources :feeds

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :favorites, only: [:create, :destroy]
  resources :blogs do
    collection do
      post :confirm
      get :top
    end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    mount_uploader :image, ImageUploader
    validates :content, presence: true, length: { maximum: 140 }
    
    belongs_to :user
    validates :user_id, presence: true
    
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
    
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    
    belongs_to :user
    belongs_to :blog
    
end

app/models/feed.rb
class Feed < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, uniqueness: true, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  has_many :blogs, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  before_action :logged_in?
  

  
  def reset_user_session
    session[:user_id] = nil
    @current_user = nil
  end  
  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :list]
  before_action :require_login
  
  def index
    #@blogs = current_user.blogs.all
    @blogs = Blog.all
  end
  
  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end
  
  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id #現在ログインしているuserのidをblogのuser_idカラムに挿入する
    if @blog.save
      
       @user = current_user
       # deliverメソッドを使って、メールを送信する
       ContactMailer.contact_mail(@user).deliver
       
       # 一覧画面へ遷移して"Pictureを登録しました！"とメッセージを表示します。
       redirect_to blogs_path, notice: "Pictureを登録しました！"
       
    else
       # 入力フォームを再描画します。
       render 'new'
    end
  end
  
  def confirm
    @blog = Blog.new(blog_params)
    render :new if @blog.invalid?
  end
  
  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end
  
  def edit
  end
  
  def top
    #ここに記述する
    @user = current_user
    @favorite_blogs = @user.favorite_blogs    
  end
  
  def update
    if @blog.update(blog_params)
       redirect_to blogs_path, notice: "Pictureを編集しました！"
    else
      render 'edit'
    end
  end
  
  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"Pictureを削除しました！"
  end

  private
  
  def require_login
    unless logged_in?
      flash[:notice] = 'Log in してください'
      redirect_to new_session_path
    end
  end  
  
  def blog_params
    params.require(:blog).permit(:content, :user_id, :image, :image_cache)
  end
  
  # idをキーとして値を取得するメソッド
    def set_blog
      #@blog = current_user.blogs.find(params[:id])
      @blog = Blog.find(params[:id])
    end
  
end

app/controllers/favorite_controller.rb
class FavoriteController < ApplicationController
    
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end    
    
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end    
    
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:image, :image_cache)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  skip_before_action :logged_in?
  
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'ログインしました'
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end  
  
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  skip_before_action :logged_in?
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'Sign up 成功！　Log in してください'
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end
  
  def show
    @user = User.find(params[:id])
    @favorite_blogs = @user.favorite_blogs
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end
  
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :comment %>
    <%= form.text_field :content %>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>
  
  <div class="blog_title">
    
    <%= form.file_field :image, class: "fileInput",style: "display:none;", id: :blog_image  %>

  </div> 
  
  <div class="input-group">
    <input type="text" id="image" class="form-control" placeholder="select file...">
    <span class="input-group-btn"><button type="button" class="btn btn-info" onclick="$('input[id=blog_image]').click();">Browse</button></span>
  </div>
  <p>jpg,jpeg,gif,png only</p>

  <script>
    $('input[id=blog_image]').change(function() {
      $('#image').val($(this).val().replace("C:\\fakepath\\", ""));
    });
  </script>
  
  <%= form.submit %>
<% end %>

<%= link_to 'Picture一覧画面にもどる', blogs_path,  class: 'btn btn-primary' %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、登録する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>

  <p>本文:<%= @blog.content %></p>
  <p>
    <strong>Image:</strong>
    <%= image_tag(@blog.image) %>
  </p>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <%= form.submit  "登録する" %>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h2>Pictureを編集する</h2>

  <%= render 'form' %>

app/views/blogs/index.html.erb
<div class="container">

  <h1>Picture一覧</h1>
  
  <div id="new-blog-link">
    <%= link_to '新規Pictureを作成する', new_blog_path, class: 'btn btn-info btn-lg' %>
  </div>
  
  <br>
  
  <p><%= notice %></p>

  <nav class="row">

    <% @blogs.each do |blog| %>
    
      <div class="container-fluid">
        <ul class="row">
          <li class="col-lg-2.4">投稿者: <%= blog.user.name%></li>
          <li class="col-lg-2.4">コメント: <%= blog.content %></li>
          <li class="col-lg-2.4"><%= image_tag blog.image.to_s %></li>
        
          <% if blog.user == current_user %>
            <li class="col-lg-2.4"><%= link_to '　詳細を確認する　', blog_path(blog.id), class: 'btn btn-default'  %></li>
            <li class="col-lg-2.4"><%= link_to 'Pictureを編集する', edit_blog_path(blog.id), class: 'btn btn-primary' %></li>
            <li class="col-lg-2.4"><%= link_to 'Pictureを削除する', blog_path(blog.id), method: :delete ,data: { confirm: '本当に削除していいですか？' }, class: 'btn btn-danger' %></li> 
          <% else %>
            <li class="col-lg-2.4"><%= link_to '　詳細を確認する　', blog_path(blog.id), class: 'btn btn-default'  %></li>
          <% end %>
          
        </ul>    
      </div>
    <% end %>
  </nav>

</div>

app/views/blogs/new.html.erb
<h2>Pictureを作成する</h2>

  <%= render 'form' %>

app/views/blogs/show.html.erb
<h1>Picture詳細画面</h1>

<p>投稿者: <%= @blog.user.name%></p>
<p>コメント: <%= @blog.content %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@blog.image) %>
</p>

<% unless @blog.user == current_user %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りにする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<%= link_to "Picture一覧画面にもどる", blogs_path, class: 'btn btn-primary' %>

app/views/blogs/top.html.erb
<div class="container">

  <h1>TOP</h1>
  <h2>ブログアプリです</h2>
  
</div>

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :feed_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.image %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @feed.image %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>

  <div class="user_title">
    
    <%= f.file_field :image, class: "fileInput",style: "display:none;", id: :user_image  %>

  </div> 
  
  <div class="input-group">
    <input type="text" id="image" class="form-control" placeholder="select file...">
    <span class="input-group-btn"><button type="button" class="btn btn-info" onclick="$('input[id=user_image]').click();">Browse</button></span>
  </div>
  <p>jpg,jpeg,gif,png only</p>

  <script>
    $('input[id=user_image]').change(function() {
      $('#image').val($(this).val().replace("C:\\fakepath\\", ""));
    });
  </script>
  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@user.image) %>
</p>

          <li id="new-blog-link">
          <%= link_to 'お気に入り一覧', top_blogs_path, class: 'btn btn-default' %>
          </li>

app/views/users/top.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@user.image) %>
</p>

    <% @favorite_blogs.each do |favorite| %>
    
      <div class="container-fluid">
        <ul class="row">
          <li class="col-lg-12"><%= favorite.content %></li>
          <li class="col-lg-12"><%= image_tag favorite.image.to_s %></li>
        
        </ul>    
      </div>
    <% end %>